name: Linter

on:
  push:
    tags-ignore:
      - '*'
    paths:
      - '**.py'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        python -c 'from foo import foo'
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 foo/ test/
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile=setup.cfg foo/ tests/*.py
