name: Deploy to PyPI

env:
  PYTHON: 3.6

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  tests:
    name: Test package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python $PYTHON
      uses: actions/setup-python@v1
      with:
        python-version: $PYTHON

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint for errors
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Install package
      run: python setup.py install

    - name: Validate test package
      run: pytest

  pypi:
    name: Deploy to PyPI
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python $PYTHON
      uses: actions/setup-python@v1
      with:
        python-version: $PYTHON

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        PYPI_URL: ${{ secrets.PYPI_URL }}
      run: twine upload --repository-url $PYPI_URL dist/*

  release:
    name: Release to Github
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
